//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculation
    {
        public int CalculationId { get; set; }
        public string MathCal { get; set; }
    }
}
