//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVDLibraryCatelogue.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dvd
    {
        public int dvdId { get; set; }
        public string rating { get; set; }
        public string director { get; set; }
        public string title { get; set; }
        public int realeaseYear { get; set; }
        public string notes { get; set; }
    }
}
